
%  NRCan CCRS Vegetation Biophysical Parameter Retrieval Tools
%
%  Main Program
%
%  Detang Zhong
%
%  Revised: 2021.01.30

%% --------- Initialization

  clear all
  close all
  format long g
  global app_dir;
  
%% --------- Define program, data and file path
  app_dir.root = cd;
  app_dir.toolsexe = [app_dir.root '\toolsexe'];
  app_dir.python = [app_dir.root '\python'];
  app_dir.loglevel = 1; % 0: don't keep log files, 1: keep log files for each step  
  
%% ---------- Add search pathes
gdal_apps_path = 'C:\gdal232exe\bin\gdal\apps';
addpath(gdal_apps_path);
addpath([app_dir.root '\Common']);
addpath([app_dir.root '\python']);
addpath([app_dir.root '\license']);
addpath([app_dir.root '\ATPRK']);
addpath([app_dir.root '\SupReME\include']);
addpath([app_dir.root '\DSen2\matlab_demo']);
addpath([app_dir.root '\VBPR']);
addpath([app_dir.root '\VBPR\aux_data']);
%addpath([app_dir.root '\SL2P_V1']);
%addpath([app_dir.root '\SL2P_V1\aux_data']);
%addpath([app_dir.root '\SL2P_V2']);
%addpath([app_dir.root '\SL2P_V2\aux_data']);
addpath([app_dir.root '\Validation']);
addpath([app_dir.root '\S2Tools']);
addpath(app_dir.root);

%% ---------- Check licence
    lic_info = LicenseGetStatus();
    if lic_info.valid < 2
        LicenseActivation;
        msgbox('To run this program, you need to get a license first!');
        return;
    end

%% ---------- Constants   
    d2r=pi/180;        
    pro_tiltle = 'NRCan CCRS VBPR Tools V1.0/2021/01/30';
         
  %% --------- Defines main window
  figure;
  main_window = gcf;
  set(main_window,'resize','off');
  set(main_window,'units','normalized')
  %set(main_window,'position',[0.1 0.1 0.5 0.5])
  set(main_window,'position',[0.25 0.25 0.6 0.4])
  set(main_window,'menubar','none')
  set(main_window,'name',pro_tiltle)
  set(main_window,'numbertitle','off')

  % Load the image
  [x,map]=imread('Start.JPG');
  imagesc(x);
  image(x); title(pro_tiltle);
  colormap(map); 
  axis off  % Remove axis ticks and numbers
  
  clear x;
   
  %% --------- Defines menus for main window
    s2_process_menu = uimenu(main_window, ...
        'label','S2 Image Processing Tools', ...
        'enable','on');
    s2_batch_process_menu = uimenu(s2_process_menu, ...
        'label','Batch Processing', ...
        'separator','off', ...
        'enable','on');
    s2_batch_L2A_process_menu = uimenu(s2_batch_process_menu, ...
        'label','Unzip S2 L1C Data and Run L2A Process',...
        'separator','off', ...
        'enable','on', ...
        'callback','UnzipSen2CorS2L1C');
    s2_batch_subset_process_menu = uimenu(s2_batch_process_menu, ...
        'label','Subset Tile Images and Unify Band Resolutions',...
        'separator','on', ...
        'enable','on', ...
        'callback','ClipSubAreaAndUnifyBandResolutions');
    
    s2_step_process_menu = uimenu(s2_process_menu, ...
        'label','Step by Step Processing', ...
        'separator','on', ...
        'enable','on');
    s2_step_L2A_process_menu = uimenu(s2_step_process_menu, ...
        'label','Unzip S2 L1C Data and Run L2A Process',...
        'separator','off', ...
        'enable','on', ...
        'callback','UnzipSen2CorS2L1C');
    s2_view_angles_menu = uimenu(s2_step_process_menu, ...
        'label','Interpolate Zenith and Azimuth Angles',...
        'separator','on', ...
        'enable','on', ...
        'callback','GenerateViewAngles');
    s2_gdal_subset_menu = uimenu(s2_step_process_menu, ...
        'label','Subset Tile Images by PCI Clip',...
        'separator','on', ...
        'enable','on', ...
        'callback','ClipSubAreaFromTileImageByPCIClip');
    s2_pci_clip_menu = uimenu(s2_step_process_menu, ...
        'label','Subset Tile Images by GDAL Translate',...
        'separator','on', ...
        'enable','on', ...
        'callback','ClipSubAreaFromTileImageByGDAL');
    s2_resample_subarea_menu = uimenu(s2_step_process_menu, ...
        'label','Unify Subset Image Band Resolutions',...
        'separator','on', ...
        'enable','on', ...
        'callback','UnifyResolutionSubarea');  


  vbpr_menu = uimenu(main_window, ...
    'label','Estimate Variables', ...
    'enable','on');
  vbpr_batch_menu = uimenu(vbpr_menu, ...
    'label','Batch Processing', ...
    'enable','on');
   sub_batch_sl2p_menu = uimenu(vbpr_batch_menu, ...
        'label','Batch Estimate Bio Variables By SL2P',...
        'separator','off', ...
        'enable','on', ...
        'callback','SUB_VBPR_By_SL2P_BATCH');
    
  vbpr_step_menu = uimenu(vbpr_menu, ...
    'label','Step by Step Processing', ...
    'separator','on', ...
    'enable','on');
   sub_step_sl2p_menu = uimenu(vbpr_step_menu, ...
        'label','Estimate Bio Variables By SL2P for a Subset',...
        'separator','off', ...
        'enable','on', ...
        'callback','SUB_VBPR_By_SL2P');
   sub_step_alr_sl2p_menu = uimenu(vbpr_step_menu, ...
        'label','Estimate Bio Variables By ALR SL2P for a Subset',...
        'separator','on', ...
        'enable','on', ...
        'callback','SUB_VBPR_By_ALR_SL2P');        

  wv3_menu = uimenu(main_window, ...
    'label','WV2 Processing Tools', ...
    'enable','on');
  wv3_batch_menu = uimenu(wv3_menu, ...
    'label','Batch Processing', ...
    'enable','on');
   sub_batch_wv3_calibrate_menu = uimenu(wv3_batch_menu, ...
        'label','Calibration Regression (20m)',...
        'separator','off', ...
        'enable','on', ...
        'callback','WV3_Calibration_Regression_Batch');
   sub_batch_wv3_apply_menu = uimenu(wv3_batch_menu, ...
        'label','Application Regression (10m)',...
        'separator','on', ...
        'enable','on', ...
        'callback','WV3_Application_Regression_Batch');
   sub_batch_wv3_compare_bio_menu = uimenu(wv3_batch_menu, ...
        'label','Compare WV3 and S2 BIO Variables (10m & 20m)',...
        'separator','on', ...
        'callback','WV3_CompareBIOVariables_Batch');
    
  wv3_step_menu = uimenu(wv3_menu, ...
    'label','Step by Step Processing', ...
    'separator','on', ...
    'enable','on');
   sub_step_wv3_filter_menu = uimenu(wv3_step_menu, ...
        'label','Blockmean WV3 Images to Selected Resolutions',...
        'separator','off', ...
        'enable','on', ...
        'callback','SpatialFilterWV3Image');
   sub_step_wv3_match_menu = uimenu(wv3_step_menu, ...
        'label','Match WV3 Images to S2 Resolution (2m -> 10m/20m)',...
        'separator','on', ...
        'enable','on', ...
        'callback','WV3_SampleMatchToS2Resolution');
   sub_step_wv3_calibrate_menu = uimenu(wv3_step_menu, ...
        'label','Calibration Regression (20m)',...
        'separator','on', ...
        'enable','on', ...
        'callback','WV3_Calibration_Regression');
   sub_step_wv3_apply_menu = uimenu(wv3_step_menu, ...
        'label','Application Regression (2m/10m/20m)',...
        'separator','on', ...
        'enable','on', ...
        'callback','WV3_Application_Regression');
   sub_step_wv3_biomatch_menu = uimenu(wv3_step_menu, ...
        'label','Resample WV3 BIO to S2 BIO Resolution (2m -> 10m/20m)',...
        'separator','on', ...
        'enable','on', ...
        'callback','MatchWV3BioToS2BioResolution');
   sub_step_wv3_compare_bio_menu = uimenu(wv3_step_menu, ...
        'label','Compare WV3 and S2 BIO Variables (10m/20m)',...
        'separator','on', ...
        'callback','CompareWV3BIOToS2BIOVariables');
   
  validate_menu = uimenu(main_window, ...
        'label','Accuracy Assessment', ...   
        'enable','on'); 
    tools_match_points_menu = uimenu(validate_menu, ...
        'label','Match Bio Estimates with InStu Measurments',...
        'separator','off', ...
        'callback','MatchToInSituData');
    tools_bio_evaluation_menu = uimenu(validate_menu, ...
        'label','Evaluate Bio Estimates by InStu Measurments',...
        'separator','on', ...
        'callback','AssessByInSituData');
    tools_compare_images_menu = uimenu(validate_menu, ...
        'label','Compare Downscaled Images against a Reference Image',...
        'separator','on', ...
        'callback','ComparePredictedToReferenceImage'); 
     
  help_menu = uimenu(main_window, ...
    'label','Help');
    open_help_menu = uimenu(help_menu, ...
    'label','Open Help File', ...
    'enable','off',...
    'callback','cb_open_help');
    open_license_menu = uimenu(help_menu, ...
    'label','Check License Status', ...
    'separator','on', ...
    'callback','LicenseActivation');
    open_about_menu = uimenu(help_menu, ...
    'label','About ...', ...
    'separator','on', ...
    'callback','LicenseVBPRPro');

                    


